fix(tooltip): improve tooltip border, tooltip usage in card story, card/link demo html
Esri/calcite-components pull request #1851
Opened 2021-03-26 19:26 UTC by caripizza

**Related Issue:** n/a

## Summary
This pr aims to fix a few style issues with `calcite-tooltip`'s Tailwind refactors (pr #1738, pr #1765).

The goal here is to a). ensure the tooltip tail doesn't appear **over** the content area, and b). ensure the tooltip's new border styles are visible.

I also noticed the tooltip wasn't working in a few places (card stories, card/link demo html), so I tried to fix those as well.

2021-03-26 19:31 UTC, caripizza commented
@driskull let me know if there's a better to achieve what you were looking for 🌞

2021-03-26 20:03 UTC, driskull requested changes
It's looking much better @caripizza!

I'm still seeing an offset on the drop shadow for the arrow though...

<img width="783" alt="Screen Shot 2021-03-26 at 1 03 04 PM" src="https://user-images.githubusercontent.com/1231455/112686738-ace38400-8e33-11eb-879a-4b4142871739.png">


Also, it seems like the tooltip has a border but popover doesn't. Should we be consistent here?

<img width="1174" alt="Screen Shot 2021-03-26 at 1 02 17 PM" src="https://user-images.githubusercontent.com/1231455/112686754-b40a9200-8e33-11eb-8c2e-b4cc1c80ab37.png">


Zooming in with osx makes it easy to see the differences.

2021-03-26 20:05 UTC, driskull commented
I think the popover is missing the rounded corners too.

2021-03-29 16:27 UTC, driskull commented
Looking good @caripizza. I see the consistent border now

![image](https://user-images.githubusercontent.com/1231455/112868360-d3dac980-9070-11eb-86d7-9623de55016a.png)

There seems to be a little bit of background bleeding through. What do you think? I'm ok with it if you guys are :)

2021-03-30 14:26 UTC, bstifle commented
dang it it's so close!

2021-03-30 14:31 UTC, bstifle commented
Tooltip and popover looking 100% perfect on my end. no bleeds

2021-03-31 22:59 UTC, driskull approved these changes
👍

2021-04-01 00:39 UTC, merged