Bpatterson88/2039 date picker styles
Esri/calcite-components pull request #2132
Opened 2021-05-12 22:44 UTC by bpatterson88

**Related Issue:** #2039 

## Summary

- [x] Fix UI bug with start and end dates where the background color rendered incorrectly.
- [x] Changes behavior of hover range and selected range so that selected range remains highlighted while hovering within it.

<img width="302" alt="Screen Shot 2021-05-12 at 3 34 58 PM" src="https://user-images.githubusercontent.com/15875886/118052522-c2573380-b337-11eb-9ff6-2be884f9aab4.png">
<img width="309" alt="Screen Shot 2021-05-12 at 3 34 54 PM" src="https://user-images.githubusercontent.com/15875886/118052720-13ffbe00-b338-11eb-9844-c72db00c3347.png">

- [ ] Fix UI bug where the hover range remains visible when the user mouses out of the calendar days but not the calendar container. 

<img width="299" alt="Screen Shot 2021-05-12 at 3 40 02 PM" src="https://user-images.githubusercontent.com/15875886/118052847-5628ff80-b338-11eb-95b1-cc1a3d5c5899.png">

2021-05-13 15:07 UTC, caripizza commented on src/components/calcite-date-picker-day/calcite-date-picker-day.scss
> +:host(:hover[start-of-range][range-hover][dir="rtl"]) .day-wrapper {
Can you use the `.calcite--rtl` class when direction is rtl - instead of having both the attribute selectors here?

2021-05-13 15:08 UTC, caripizza commented on src/components/calcite-date-picker-day/calcite-date-picker-day.scss
> +:host(:hover[end-of-range][range-hover][dir="rtl"]) .day-wrapper {
same comment here, use `calcite--rtl` class for rtl

2021-05-13 15:10 UTC, caripizza commented on src/components/calcite-date-picker-month/calcite-date-picker-month.tsx
> +  private isHoverInRange(): boolean {
nitpick: remove whitespace addition

2021-05-13 15:10 UTC, caripizza commented on src/components/calcite-date-picker-day/calcite-date-picker-day.scss
> +:host(:hover[range-hover]:not([selected]).focused--start[dir="rtl"]) {
use `calcite--rtl` class for rtl

2021-05-13 15:10 UTC, caripizza commented on src/components/calcite-date-picker-day/calcite-date-picker-day.scss
> +:host(:hover[range-hover]:not([selected]).focused--end[dir="rtl"].hover--outside-range) {
use `calcite--rtl` class for rtl

2021-05-13 15:10 UTC, caripizza commented on src/components/calcite-date-picker-day/calcite-date-picker-day.scss
> +:host(:hover[range-hover]:not([selected]).focused--start[dir="rtl"].hover--outside-range) {
use `calcite--rtl` class for rtl

2021-05-13 15:11 UTC, caripizza commented on src/components/calcite-date-picker-day/calcite-date-picker-day.scss
> +:host([range-hover][dir="rtl"]:not([selected]):last-child) .day-wrapper {
use `calcite--rtl` class for rtl

2021-05-13 15:13 UTC, caripizza requested changes
Thanks @bpatterson88! Couple comments relating to our new rtl approach, otherwise looking good to me.

2021-05-13 15:13 UTC, caripizza commented
I also would have expected Screener tests to fail on this one, which is odd. 🤔

2021-05-13 15:28 UTC, julio8a commented
looping in @eriklharper on screener ^

2021-05-14 16:09 UTC, caripizza commented
This looks great to me @bpatterson88! @bstifle can you be sure the new hover styles here look good?

2021-05-14 16:19 UTC, bstifle commented
blasted screener! ill check now

2021-05-14 16:23 UTC, bstifle commented
ok so pretty good @bpatterson88 

just some issues on the numbers that live on the edges of the weeks:
<img width="73" alt="Screen Shot 2021-05-14 at 11 21 55 AM" src="https://user-images.githubusercontent.com/14083530/118299765-c5246680-b4a6-11eb-8e42-8c6eb505dee3.png">
<img width="56" alt="Screen Shot 2021-05-14 at 11 21 36 AM" src="https://user-images.githubusercontent.com/14083530/118299767-c5246680-b4a6-11eb-88f8-5c4a804989a1.png">
<img width="58" alt="Screen Shot 2021-05-14 at 11 21 32 AM" src="https://user-images.githubusercontent.com/14083530/118299768-c5bcfd00-b4a6-11eb-9e4c-8b19c9ff347f.png">




<img width="29" alt="Screen Shot 2021-05-14 at 11 22 21 AM" src="https://user-images.githubusercontent.com/14083530/118299759-c3f33980-b4a6-11eb-9ba6-747331b3442d.png">
<img width="50" alt="Screen Shot 2021-05-14 at 11 22 18 AM" src="https://user-images.githubusercontent.com/14083530/118299761-c48bd000-b4a6-11eb-9347-014f524011f6.png">
<img width="66" alt="Screen Shot 2021-05-14 at 11 21 58 AM" src="https://user-images.githubusercontent.com/14083530/118299764-c48bd000-b4a6-11eb-9bbf-07b0a2367b33.png">


small appears to be unaffected, but this is happening on M and L

2021-05-14 20:47 UTC, bpatterson88 commented
@bstifle fixed the color bleed.
<img width="108" alt="Screen Shot 2021-05-14 at 1 42 30 PM" src="https://user-images.githubusercontent.com/15875886/118326778-4c2f0a00-b4ba-11eb-9ec8-5462cb3eefe8.png">

I've been unable to fix the awkward hover state seen on Sep 3 in the screen shot below. It happens when the mouse is not longer over a day, but is still within the calendar component (ex. hovering over the day-of-week labels). It goes away as soon as the user leaves the calendar though.
<img width="394" alt="Screen Shot 2021-05-14 at 1 43 45 PM" src="https://user-images.githubusercontent.com/15875886/118326947-6bc63280-b4ba-11eb-9c4f-0cc412cf69de.png">

2021-05-17 16:54 UTC, bstifle commented
Oh nice, bleed looks good!



Yeah weird that the edge gets square when hovering away... @macandcheese or @caripizza any remedy for that?

2021-05-19 00:03 UTC, caripizza approved these changes
@bstifle No easy way to fix unfortunately. I vote we handle that in a follow up issue since this one fixes all those other hover issues we were seeing. Thanks @bpatterson88 looks great! 👍

2021-05-19 19:33 UTC, merged