refactor(modal): updated headers and spacing
Esri/calcite-components pull request #2206
Opened 2021-05-25 18:04 UTC by julio8a

**Related Issue:** #1500

## Summary

- Updated header text for s, m, l
- Updated all spacing to match Figma

Working from the [Figma/Tailwind components refactor project](https://github.com/Esri/calcite-components/projects/14)

https://github.com/Esri/calcite-components/projects/14#card-60668030

2021-05-26 15:03 UTC, asangma requested changes
Just one request.

2021-05-26 15:04 UTC, asangma commented on src/components/calcite-modal/calcite-modal.scss
> +  @apply leading-6;
cc @mitc7862

2021-05-26 18:42 UTC, bstifle commented
@julio8a can we drop the X on Small to 16x16 px icon?

2021-05-26 18:52 UTC, julio8a commented on src/components/calcite-modal/calcite-modal.scss
> +  @apply leading-6;
Yeah, short-term, I can remove this line height.

2021-05-26 19:26 UTC, julio8a commented
Just pushed some updates:
- small modal 'x' uses scale=s of calcite-icon
- removed line-height from slotted content

2021-05-26 21:41 UTC, julio8a commented
Okay, I think this is ready for another review.

2021-05-26 23:12 UTC, bstifle approved these changes
PERFECT

2021-05-27 00:05 UTC, asangma approved these changes
Thanks @julio8a! 

🧹 ✨

2021-05-27 00:05 UTC, merged