test(alert): update demo html to match Figma #2436
Esri/calcite-components pull request #2486
Opened 2021-07-08 00:01 UTC by ManahariDahal

**Related Issue:** #2436

## Summary
- matched the current calcite-alert demo page according to the Figma design 
- DOM manipulation works as intended and is inside the <style> tag 
- demo video attached
- will update the video with recent changes

https://user-images.githubusercontent.com/23712621/124842512-8a89f800-df44-11eb-9e1b-d6c4bfc502bf.mov

2021-07-08 16:36 UTC, bstifle commented
![image](https://user-images.githubusercontent.com/14083530/124958969-59f79c00-dfe0-11eb-9f02-983fb5e3a350.png)

1. let's drop these labels down to avenir-medium for the weight


![image](https://user-images.githubusercontent.com/14083530/124959071-7693d400-dfe0-11eb-966f-99c4fde9965a.png)
![image](https://user-images.githubusercontent.com/14083530/124959207-9925ed00-dfe0-11eb-8018-d808fbcd075a.png)

2. let's make the audodismiss speed selector a radio-group with the selection clear appearance


![image](https://user-images.githubusercontent.com/14083530/124959273-a9d66300-dfe0-11eb-9f0f-31a118886fc1.png)

3. the "using the serFocus()"  doesn't seem to work

2021-07-08 20:57 UTC, ManahariDahal commented
I realized there were some recent changes with the addition of the sizes _small_, _medium_, and _large_. 
![Screen Shot 2021-07-08 at 11 16 56 AM](https://user-images.githubusercontent.com/23712621/124989701-448c6d00-dff4-11eb-8ae7-648e7c616398.png)

However, the Figma design already encompasses them. Let me know if I should keep them. The current design is the one on the video attached above.

2021-07-13 21:12 UTC, julio8a commented on src/demos/calcite-alert.html
> +                  .__(.)< (MEOW)
Remove the MEOW comment

2021-07-13 21:16 UTC, julio8a requested changes
This is great! left a comment to remove the meow comment. Also, not sure if we need these:
- Alerts inserted into the DOM programmatically
- Using the setFocus() method (once opened)

I think we can remove them, what do you think @caripizza?

2021-07-13 21:54 UTC, caripizza commented
@julio8a I personally like having those examples. It gives us the ability to manually test the behavior in multiple browsers.

2021-07-13 21:56 UTC, julio8a commented
Thanks, @caripizza! let's leave them . :)

2021-07-15 00:47 UTC, bstifle approved these changes
lookin good manahari!

2021-07-15 15:46 UTC, caripizza commented on src/demos/calcite-alert.html
> +    <!-- Internal style -->
Can we remove the notes like this?

2021-07-15 15:46 UTC, caripizza commented on src/demos/calcite-alert.html
> +            let alert = document.getElementsByTagName("calcite-alert");
use `const`

2021-07-15 15:49 UTC, caripizza commented on src/demos/calcite-alert.html
> +        * MEDIUM PROP
Let's use the prop name `scale` ("MEDIUM SCALE" or similar)

2021-07-15 18:29 UTC, ManahariDahal reviewed
fixed all of the requested changes

2021-07-16 18:09 UTC, julio8a approved these changes
LGTM

2021-07-16 18:20 UTC, caripizza commented on src/demos/calcite-alert.html
> +              value="Moderate"
Let's match the name of the prop value, "Medium"

2021-07-16 18:22 UTC, caripizza commented on src/demos/calcite-alert.html
> +          <p>Autodismiss speed</p>
Can we match verbiage with the prop? "Auto-dismiss"

2021-07-16 18:26 UTC, caripizza commented
@ManahariDahal looks great! Can you add a slotted link or close button inside one of the auto-dismiss examples? It'll be nice to test with the "Focus first item" button too.

2021-07-16 23:11 UTC, julio8a commented
This one ready to merge?

2021-07-16 23:26 UTC, ManahariDahal commented
> This one ready to merge?

yep, everything seems to work fine

2021-07-16 23:27 UTC, merged