refactor(calcite-input)
Esri/calcite-components pull request #2533
Opened 2021-07-14 16:40 UTC by bpatterson88

### WIP

**Related Issue:** #2041 #2455

## Summary

- Adjusted input scale
- Refactored CSS to use tailwind
- Updated X icon in close button to be text-color-1 on hover (#2216)

2021-07-14 16:50 UTC, julio8a commented
I'm wondering what's the best way to approach this. Currently, a few other components use input and other components that depend on the input, i.e. button (height match). 
* Color picker
* Date picker
* inline editable
* Button

I'm wondering if we want to merge these into a separate branch to not break other components. Any thoughts on this @jcfranco @caripizza?

2021-07-14 17:48 UTC, jcfranco commented
> I'm wondering if we want to merge these into a separate branch to not break other components. Any thoughts on this

For this one, I think a separate branch to update input along with all of its dependents makes sense and it'd be way cleaner too.

2021-07-19 18:47 UTC, bpatterson88 commented
This is ready for a review @bstifle

2021-07-19 23:00 UTC, macandcheese reviewed
This looks great @bpatterson88 - thanks for taking this on!

It looks like the sizing changes mean there are some needed updates on components that consume `<calcite-input>` - at least `calcite-input-date-picker`:

<img width="1274" alt="Screen Shot 2021-07-19 at 3 58 27 PM" src="https://user-images.githubusercontent.com/4733155/126238082-fa6a43f7-f7ab-44cb-a685-4c17691780d3.png">

cc @bstifle

2021-07-19 23:07 UTC, julio8a commented
Yeah, I think from previous comments https://github.com/Esri/calcite-components/pull/2533#issuecomment-880089754 we'll need to wait on merging into master until some components have been refactored (i.e. buttons, inline editable, color-picker, etc).

@caripizza what branch should we be merging these component refactors into?

2021-07-20 00:45 UTC, caripizza commented
@julio8a we can create a brand new branch (ex: "tw-button-input-refactors"), and merge both button and input refactor pr branches into it. (Then open pr, and merge the tw-button-input-refactors branch into master when we're ready.)

Or, we can use one pr as the base branch (ex: this input pr). That would involve merging the button refactor branch into this one. (Then we'd merge this input pr into master.)

I'll work with @bpatterson88 on the logistics this week so we can coordinate!

2021-07-28 16:43 UTC, caripizza commented
@bstifle @julio8a @macandcheese can you guys help checking that this one looks good as far as UI goes? (If so, I'll merge pr #2663 into it, so that this one can be merged into master.)

2021-07-28 16:55 UTC, bstifle commented
dang these are looking so stinkin good @caripizza @bpatterson88 


only thing im seeing is on the number input there is some extra border going on with the RTL one

![image](https://user-images.githubusercontent.com/14083530/127364430-9e224adf-4641-4452-9076-92d98fbb6807.png)

2021-07-28 16:58 UTC, bstifle commented
![image](https://user-images.githubusercontent.com/14083530/127364636-7e51f02a-df4d-4b13-9121-fd18877b60c5.png)

@caripizza will these be addressed in the other issue? #2663

2021-07-28 17:00 UTC, caripizza commented
Yep @bstifle - check out that other pr branch for all of the heights changes together

2021-07-28 17:34 UTC, julio8a commented
I noticed these button are taller than the input, might just need a demo update?
![image](https://user-images.githubusercontent.com/6144462/127369657-c7d5f03b-d20d-465c-9d16-2715dbba57b5.png)

2021-07-28 17:39 UTC, caripizza commented
@julio8a you need to check out the other pr branch to see all the input + button styles together

2021-07-28 18:30 UTC, julio8a approved these changes
Really nice work! <3

2021-07-29 00:06 UTC, bpatterson88 commented
@bstifle Removed the extra border on the RTL vertical spinner

2021-07-29 01:04 UTC, caripizza requested changes
Looking really great Ben! Just a few cleanup items that I see - thanks again for all your help on this one.

2021-07-29 01:04 UTC, caripizza commented on src/components/calcite-input/calcite-input.tsx
> +        <calcite-icon icon="x" scale='s' />
nitpick: use double quotes `scale="s"`

2021-07-29 01:04 UTC, caripizza commented on tailwind.config.js
> +        },
can remove the trailing whitespace?

2021-07-29 15:40 UTC, bstifle commented
@bpatterson88 lookin REAL nice. been too long, ye oldé 𝓲𝓷𝓹𝓾𝓽

2021-07-29 16:52 UTC, caripizza commented
@driskull and/or @eriklharper can you guys review this one now that we have both pr branches together?

2021-07-29 16:58 UTC, driskull approved these changes
Reviewed the TSX files.

2021-07-29 16:58 UTC, driskull commented on src/components/calcite-color-picker/calcite-color-picker.tsx
> +                scale={this.scale === "l" ? "m" : "s"}
nitpick: Seems like `this.scale === "l" ? "m" : "s"` is used a few times. Maybe it could be put into a const?

2021-07-29 16:58 UTC, driskull commented on src/components/calcite-input-date-picker/calcite-input-date-picker.tsx
> +                  class={`input ${
Can we use an object for class?

```tsx
class={{
input: true,
"border-t-color-1": this.layout === "vertical" && this.range
}}
```

2021-07-29 18:27 UTC, caripizza approved these changes

2021-07-29 18:31 UTC, caripizza commented
@julio8a @bstifle can you approve the Screener changes if they look good so I can merge this one to master?

2021-07-29 19:06 UTC, merged