test(color-picker): updated calcite-color-picker demo page
Esri/calcite-components pull request #2578
Opened 2021-07-20 21:29 UTC by ManahariDahal

**Related Issue:** #2576 

## Summary
- updated calcite-color-picker encompassing the Figma design
- this version includes small, medium, and large width & scale, which the previous version failed to include

2021-07-20 22:24 UTC, bstifle approved these changes
NICE! perf

2021-07-22 22:46 UTC, julio8a commented
is this a bug with the component?
![image](https://user-images.githubusercontent.com/6144462/126718017-faee5d0f-0f3e-44d1-a8bc-d88085d12ddb.png)
Should this one be empty (no color selected) based on the prop ^

Also, I don't see a visual difference between default, default (no color), with initial color (there than a different color selected), and store saved colors. 

Therefore, do we need these and just depend on default?

cc'ing @bstifle @jcfranco

2021-07-22 23:31 UTC, jcfranco commented
> Also, I don't see a visual difference between default, default (no color), with initial color (there than a different color selected), and store saved colors.

The no-color example requires users to clear the number to see a visual difference in the UI. We could update the code so that the color picker is empty by default: 

```html
<calcite-color-picker allow-empty value=""></calcite-color-picker>
```

The store-saved-colors example requires saving colors and reloading the page to see a visual difference.

2021-07-30 21:20 UTC, ManahariDahal commented
@julio8a this is ready to be reviewed.

2021-07-30 23:05 UTC, julio8a commented
Thanks! I don't think we need these:

* With initial color
  * The default starts with initial color
* Stored saved color
  * There are no stored colors on load

@jcfranco, is there a way to have this component start up some stored colors?

2021-08-05 20:58 UTC, julio8a commented
@jcfranco, any thoughts on the stored colors on load?

2021-08-05 21:02 UTC, jcfranco commented
I think it can be removed for now. The demo page would possibly have something for this use case once https://github.com/Esri/calcite-components/issues/748 is implemented. In the meantime, there is an E2E test that will cover it.

2021-08-06 19:10 UTC, julio8a requested changes
@ManahariDahal, please remove `with initial color` and `stored saved color`

2021-08-06 19:12 UTC, ManahariDahal commented
> @ManahariDahal, please remove `with initial color` and `stored saved color`

oops, forgot to push the latest changes.

2021-08-06 19:20 UTC, julio8a approved these changes
Nice!

2021-08-06 20:36 UTC, merged