test: Fix accordion demo to pass aXe.
Esri/calcite-components pull request #2650
Opened 2021-07-26 23:29 UTC by driskull

**Related Issue:** N/A

## Summary

test: Fix accordion demo to pass aXe.

- Replace toggles template with nav
- Use template file for common styles and toggling page properties
- Add HTML5 semantic elements to pass aXe
- Remove use of inline styles
- Add image alt attributes to pass aXe

2021-07-26 23:32 UTC, driskull commented on src/demos/_assets/nav.html
> +<template>
We could call this file `demo-template.html` and `demo-template.ts` if that makes more sense.

2021-07-26 23:34 UTC, driskull commented
If this is approved, we should update each demo to make sure it's passing aXe and will therefore ensure more accurate accessibility testing results. cc @jcfranco @julio8a

2021-08-05 21:46 UTC, julio8a requested changes
If we're going to move forward with something like this @bstifle had a nice design for the toggles and the header section for all demo pages:

<img width="1599" alt="image" src="https://user-images.githubusercontent.com/6144462/128425163-f4241f80-649b-4e22-87ea-e7a68a75a9d2.png">


<img width="1593" alt="image" src="https://user-images.githubusercontent.com/6144462/128425186-68786430-5ced-4471-b69b-2e6c222e2fde.png">


<img width="1596" alt="image" src="https://user-images.githubusercontent.com/6144462/128425224-7603f328-56fa-4216-8525-53269a1354a0.png">

However, @caripizza mentioned that having the `dir` toggle doesn't work as well. I don't understand the technical detail, but @caripizza, you can chime in here.

2021-08-05 21:49 UTC, driskull commented
For the top bar, we only probably need to toggle the dark theme and RTL. Toggling everything `loading` or `disabled` doesn't make sense.

2021-08-05 22:41 UTC, asangma commented
This is great! I'd be happy to lose the floating annoyance.
I agree that we probz don't need an app-level toggle for disabled and loading. That seems like something the test app can add per component.

re: toggles
It might be nice to have the buttons be switches labelled "Dark theme" and "RTL". And have them be off by default.

2021-08-05 22:42 UTC, driskull commented
I'll update the HTML to use the `calcite-switch`'s

2021-08-05 23:00 UTC, asangma commented
> mentioned that having the dir toggle doesn't work as well

@driskull Will it work to set the `dir` on `main` so that the toggles don't move?

2021-08-05 23:01 UTC, asangma commented
@julio8a Is the full design needed for this update? If so, do you know the components for that design?

2021-08-05 23:13 UTC, julio8a commented
No, full design not needed. Manahari has been working with Bryan on the component design for all the demo pages.

2021-08-05 23:13 UTC, driskull commented
Updated header with a rough design. Let me know if thats a good enough starting point @asangma

2021-08-06 17:38 UTC, bstifle commented
> For the top bar, we only probably need to toggle the dark theme and RTL. Toggling everything `loading` or `disabled` doesn't make sense.

agreed on this.

I think leaving them switches is best. more clear ux. 


Also, that header section should be sticky to the top. currently you have to scroll all the way to the top of the page to go home. (would also keep the switches readily accessible)

2021-08-06 17:39 UTC, driskull commented
If someone could take over the styling part that would be awesome. 🌈

2021-08-06 18:27 UTC, julio8a commented
@ManahariDahal can take over this one and work with @bstifle.

2021-08-10 20:48 UTC, asangma commented
@julio8a I can take on the styling of the demo header.

2021-08-10 20:48 UTC, julio8a commented
Okay, please work with @bstifle if needed.

2021-08-11 23:22 UTC, asangma commented
@driskull Aside from setting `display: none` on the header, is there an easy way we can turn off the demo header when need be?

The shell demos (full page demos) suffer from having the demo header in there.

2021-08-11 23:24 UTC, driskull commented
@asangma what did you have in mind? Do you want a url param, escape key to close, close button on the header?

2021-08-11 23:24 UTC, driskull commented
A close button on the header is probably the best solution.

2021-08-11 23:28 UTC, bstifle commented
Looking super good pals. love it! 💯

2021-08-11 23:31 UTC, asangma commented
@driskull Hmmm...a URL param might be nice so that one doesn't have to hit a close button every time. Could also just be a js var.

2021-08-11 23:35 UTC, driskull commented
Can we add a close button to the UI and I can add url param support after merge?

2021-08-11 23:36 UTC, asangma commented
@driskull Yeah...I think a close button and/or URL param can wait. For my purposes, I can just CSS hide the header in those full page apps for now.

2021-08-11 23:46 UTC, driskull commented
What do you want the url param to be? `headless`, `no-header`, `header-disabled`?

2021-08-11 23:51 UTC, asangma commented
`header-disabled` seems to match our pattern.

2021-08-11 23:52 UTC, driskull commented
DONE

2021-08-12 15:39 UTC, asangma commented
Yew! Thanks @driskull!

2021-08-12 17:02 UTC, driskull commented
@julio8a can you approve?

2021-08-12 18:22 UTC, asangma commented
@bstifle and @rmstinson were seeing a UI bug that @driskull and I are not seeing. I say we approve and murgle and see if the UI bug persists after murgling.

2021-08-12 23:50 UTC, asangma commented
FYI. UI bug that @bstifle reported is not specific to this PR.

2021-08-13 15:06 UTC, bstifle commented
Head is cool. but im not seeing the lines on dark theme:

![image](https://user-images.githubusercontent.com/14083530/129377708-f6e09da2-07eb-4fda-8808-320198f3a5da.png)

![image](https://user-images.githubusercontent.com/14083530/129377743-f735aea3-505a-46a2-a482-d49ebbdbcc9d.png)

2021-08-13 15:07 UTC, asangma commented
@bstifle That issue is not specific to this PR. Suggest creating a new issue for what you're seeing.

2021-08-13 15:11 UTC, bstifle commented
@caripizza @driskull related to this: https://github.com/Esri/calcite-components/pull/2772

still in the works?

2021-08-13 15:17 UTC, bstifle commented
![image](https://user-images.githubusercontent.com/14083530/129381091-66038364-fb72-497e-b9dd-499682e92d80.png)
just noticed this too haha! Z-axis issue?

2021-08-13 15:34 UTC, asangma commented
re: z-index issue.
I'll have a look at that.

2021-08-13 16:27 UTC, driskull commented
Create separate issues for those. Lets not hold this up

2021-08-13 16:43 UTC, asangma commented
@driskull Done.

2021-08-13 16:46 UTC, driskull commented
The components that are going over the header need to have a `position:relative` on their host most likely. Their zIndex shouldn't be leaking out.

2021-08-13 16:54 UTC, julio8a approved these changes

2021-08-13 17:00 UTC, merged