refactor(tip, tip-group, tip-manager) relocate base :host styles, style changes to match figma
Esri/calcite-components pull request #2792
Opened 2021-08-11 23:12 UTC by rmstinson

**Related Issue:** #2471

## Summary
Relocated the base :host styles for the component. Made style changes for the tip-manager to match style in Figma!

2021-08-18 03:21 UTC, bstifle commented
@rmstinson yo!

so, theres not enough in the demo page to give this an accurate review.

Can you add tip, tip-group and some iterations of those?

2021-08-18 16:41 UTC, bstifle commented
![image](https://user-images.githubusercontent.com/14083530/129937284-cdd1fb62-21f5-43fe-895d-8941a319f0a9.png)
1. tip-group's padding and close X hit state is a little wonky. can we get that flush to the right edge?


2. tip-manager needs some work:
- The close button should be size M (24px)
- close button should have no padding around it (see hover/press). should be edge to edge
- padding all around needs another pass. see figma: https://www.figma.com/file/E3SB0i5wPy7AagB7KcjF05/?node-id=1183%3A20943
- the < > paginations are using action M, lets change that to scale S.

2021-08-18 19:48 UTC, bstifle commented
@justinhough yo, last minute change if you can. Could get the dividing border on tip-manager to use border-3? This will match modal and date-picker to be more conhesive

2021-08-18 20:18 UTC, bstifle approved these changes
Lookin good!!! ✅ ✔️

2021-08-20 00:15 UTC, asangma requested changes
Just a few things and an update to the Action scale in pagination.

2021-08-20 00:15 UTC, asangma commented on src/components/calcite-tip-manager/calcite-tip-manager.scss
> +  //--calcite-tip-max-width: 600px;
cleanup comment.

2021-08-20 00:15 UTC, asangma commented on src/components/calcite-tip-manager/calcite-tip-manager.scss
> +  font-size: var(--calcite-font-size--1);
Use `@apply` here.

2021-08-20 00:15 UTC, asangma commented on src/components/calcite-tip-manager/calcite-tip-manager.scss
> +}
Should this have styles in it?

2021-08-20 00:15 UTC, asangma commented on src/components/calcite-tip-manager/calcite-tip-manager.scss
> +.header.header {
This should probably just be `.header`.

2021-08-20 00:15 UTC, asangma commented on src/components/calcite-tip-manager/calcite-tip-manager.scss
> +  // animation-timing-function: $easing-function;
cleanup comment.

2021-08-20 00:15 UTC, asangma commented on src/components/calcite-tip-manager/calcite-tip-manager.scss
> +  margin-top: 1px;
Use `@apply` for this.

2021-08-23 19:24 UTC, julio8a commented on src/components/calcite-tip-manager/calcite-tip-manager.tsx
> +            scale="m"
This one is M, did you mean something different?

2021-08-23 21:28 UTC, bstifle commented on src/components/calcite-tip-manager/calcite-tip-manager.tsx
> +          scale="s"
The Action should be M, which means the icon should be scale S

2021-08-23 21:29 UTC, bstifle commented on src/components/calcite-tip-manager/calcite-tip-manager.tsx
> +            scale="m"
The Action should be M, which means the icon should be scale S

2021-08-25 15:56 UTC, asangma commented on src/components/calcite-tip-manager/calcite-tip-manager.tsx
> +            scale="m"
My mistake.

2021-08-25 15:58 UTC, asangma requested changes
A couple minor things and a formatting nitpick.

2021-08-25 15:58 UTC, asangma commented on src/components/calcite-tip/calcite-tip.scss
> +    text--1h;
This is missing the wildcard selector and box-border style from the component-host partial.

2021-08-25 15:58 UTC, asangma commented on src/components/calcite-tip-manager/calcite-tip-manager.scss
> +  @apply block box-border bg-foreground-1 text-color-2 text--1h;
nitpick: when there are more than three rules, put styles on individual lines.

2021-08-30 20:03 UTC, julio8a approved these changes

2021-08-30 20:24 UTC, merged