refactor(Rating): match Figma and utilize Tailwind
Esri/calcite-components pull request #2811
Opened 2021-08-13 20:30 UTC by justinhough

**Related Issue(s):** #2810 (originally part of #2041)

## Summary

Updated heights for S `24px`, M `32px`, and L `44px` to work without chip active

2021-08-13 20:36 UTC, julio8a approved these changes
Visually, looks good! I do see the 24, 36, and 44 when inspecting without label. 👍

2021-08-16 17:08 UTC, caripizza requested changes
Looking good @justinhough! Left a couple comments on flex additions that can be removed. Instead, we can target the existing [`.fieldset`](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-rating/calcite-rating.scss#L35) and [`.star`](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-rating/calcite-rating.scss#L50) selectors in the stylesheet to change their displays to `inline-flex` or `flex`.

2021-08-16 17:08 UTC, caripizza commented on src/components/calcite-rating/calcite-rating.scss
> +  @apply flex h-8;
remove `flex` here too

2021-08-16 17:08 UTC, caripizza commented on src/components/calcite-rating/calcite-rating.scss
> +  @apply flex h-11;
remove `flex` here too

2021-08-16 17:08 UTC, caripizza commented on src/components/calcite-rating/calcite-rating.scss
> +  @apply flex;
Remove this chunk of code too

2021-08-17 17:32 UTC, julio8a commented
@caripizza, can you give this one another review?

2021-08-17 21:35 UTC, caripizza approved these changes
👍  Can you remove the extra line of whitespace and re-merge in master branch?

2021-08-17 22:01 UTC, justinhough commented
@caripizza Both have been completed.

2021-08-18 18:00 UTC, julio8a commented
This PR has unrelated test failure, going to move forward with merging.

2021-08-18 18:00 UTC, merged