test(demo-homepage): updated demo homepage, search bar has bugs
Esri/calcite-components pull request #2883
Opened 2021-08-23 21:23 UTC by ManahariDahal

**Related Issue:** #2863 

## Summary
- `demo` homepage updated
- search bar is not working yet (review required)

2021-08-23 22:38 UTC, macandcheese requested changes
Design is looking pretty good! Some comments on the filtering.

2021-08-23 22:38 UTC, macandcheese commented on src/index.html
> +      console.log(flex);
Remove console log.

2021-08-23 22:38 UTC, macandcheese commented on src/index.html
> +          item.querySelector("a calcite-tile-select[heading]").textContent.toLowerCase().startsWith(value)
You can access the heading property like:

` item.querySelector("a calcite-tile-select").heading`

You might also want to ensure value is `toLowerCase`.

2021-08-23 22:38 UTC, macandcheese commented on src/index.html
> +          item.querySelector("a calcite-tile-select[heading]").textContent.toLowerCase().startsWith(value)
It might be nice to be less restrictive than `startsWith` - for instance searching "list" should return items that don't start with "list".

2021-08-24 20:25 UTC, bstifle reviewed
Suggestion to simplify header area:
![image](https://user-images.githubusercontent.com/14083530/130684915-1804974d-8fd8-407b-8c82-4aae94c8fd87.png)

As it was a noble task to find calcite-ui-icons to match each component concept.... i think this is actually less readable, and less utility than the current layout with all links. On a 27 inch monitor, half of the components sit below the fold. On a laptop, about 3/4 of them fall below the fold. As it looks cool, these issues will inevitably slow down people using the demo page.
![image](https://user-images.githubusercontent.com/14083530/130684665-948f6dc2-f8cc-489b-9a28-3d3e89c0f3c7.png)

2021-08-24 21:29 UTC, bstifle commented
Design update suggestion:

(using action scale small, and then use the same calcite-ui-icons that you had in the tiles)

![Homepage update](https://user-images.githubusercontent.com/14083530/130692497-da4d24c5-db5b-46dc-9eee-da55729cd32a.png)

2021-09-01 00:23 UTC, driskull commented
What's the status of this PR. @julio8a should this be moved to new milestone?

2021-09-01 02:43 UTC, ManahariDahal commented
> What's the status of this PR. @julio8a should this be moved to new milestone?

Even though my internship ended, I wouldn't mind working on it, but I understand that I have lost all my credentials since I am no longer working at ESRI.

The homepage is good to go. I couldn't find any issues with it. If someone can just pull this PR, fix Travis CI, and push it from a new PR, then that should be good.

2021-09-02 23:17 UTC, julio8a commented
it looks like `calcite-input-time-picker.e2e.ts` continues to be a failing test. @jcfranco, how can we proceed with this PR?

2021-09-02 23:30 UTC, julio8a commented
@jcfranco or @driskull can you give this a code review?
@macandcheese can you give this another design review?

2021-09-03 00:22 UTC, jcfranco approved these changes
Code changes _look_ good to me. 👍🏼

2021-09-03 19:52 UTC, julio8a commented
@macandcheese can you give this one a design review

2021-09-03 20:13 UTC, macandcheese commented
Yeah I think this is good. It's a little weird to be using a calcite link inside an anchor tag - they could just be buttons or plain text links at this point. But overall it's a real nice improvement on what we currently have so let's merge it in!

2021-09-03 20:13 UTC, macandcheese approved these changes

2021-09-03 22:14 UTC, merged

2021-09-04 01:56 UTC, jcfranco commented
@julio8a FYI, I reverted this to stabilize the build and submitted https://github.com/Esri/calcite-components/pull/2983 to restore these updates once we get that build to pass.

2021-09-04 01:58 UTC, julio8a commented
Thanks Franco