fix(checkbox): resize calcite-checkbox when unchecked & focusout
Esri/calcite-components pull request #2995
Opened 2021-09-08 23:27 UTC by anveshmekala

**Related Issue:** #2880 

## Summary
This fixes the `calcite-checbox` size shrink when it is unchecked & focusout and matches with size of checkbox when checked set to true

2021-09-10 23:14 UTC, macandcheese requested changes
The sizing change here is good, but we need to make sure the outline is the same color as the background here:

![Screen Shot 2021-09-10 at 4 09 56 PM](https://user-images.githubusercontent.com/4733155/132926658-7f8f18c1-e2cd-4c95-b8e6-fce09fa12012.png)

Applying `box-shadow: inset 0 0 0 1px var(--calcite-ui-brand)` for the`[checked]` and `[indeterminate]` states should work.

2021-09-13 17:35 UTC, julio8a commented
@Esri/calcite-components-reviewers should screener fail on this one?

2021-09-13 17:40 UTC, anveshmekala commented
@julio8a  It should have . We removed `shadow-outline-active` for the `[checked]`state which shrinks the border by 1px.

2021-09-17 17:37 UTC, caripizza commented
@anveshmekala can you re-merge in master to see if Screener catches the change and fails? 

If it doesn't, I'm wondering maybe if it's due to the fact that this pr branch was created before the Screener config update.

2021-09-17 17:42 UTC, anveshmekala commented
@caripizza sounds good.  Will re-megre and see if the screener catches the issues.

2021-09-17 19:07 UTC, anveshmekala commented
@caripizza  Screener test has passed and don't see any failure. Any thoughts?

2021-09-17 19:24 UTC, caripizza approved these changes
👍  @anveshmekala I'm not sure what's up with Screener, but we can debug that 1px diff issue in a subsequent pr.

2021-09-20 21:10 UTC, merged