test(slider): add e2e test to verify maxValue capped to max prop
Esri/calcite-components pull request #3302
Opened 2021-10-19 21:53 UTC by anveshmekala

**Related Issue:** #3142

## Summary

This PR adds an `e2e` test to verify if the max value of the` calcite-slider` is capped to the provided `max` prop value

2021-11-02 17:01 UTC, caripizza requested changes
@anveshmekala thanks for trying to tackle the root cause. But for now, I think this pr should only be a test since that is the pr title and it was specifically requested here: https://github.com/Esri/calcite-components/pull/3262#issuecomment-946072101

Can you please assert the logic you added in your prior pr on this one?

Then, open a new GitHub issue + pr for the additional "root cause" fix you're adding here. Please let me know if you have questions about this approach.

2021-11-02 18:52 UTC, anveshmekala commented
> @anveshmekala thanks for trying to tackle the root cause. But for now, I think this pr should only be a test since that is the pr title and it was specifically requested here: [#3262 (comment)](https://github.com/Esri/calcite-components/pull/3262#issuecomment-946072101)
> 
> Can you please assert the logic you added in your prior pr on this one?
> 
> Then, open a new GitHub issue + pr for the additional "root cause" fix you're adding here. Please let me know if you have questions about this approach.
@caripizza  I think we should open a new issue to fix the bug introduced with the PR #3262 which doesn't append the classname `.thumb--maxValue`. It can be solved by fixing the root cause . We can close this PR and have the test added in the new issue. Any thoughts on this approach ?

2021-11-02 22:48 UTC, caripizza commented
@anveshmekala it's not the thumb class that fails to render, it's the max tick label class.

On this pr, you can use the original selector in the e2e test from my first comment before I edited it (`const maxTickLabel = await page.find("calcite-slider >>> .tick:nth-of-type(11)");`.)

You can give the new issue a title like "Bug: [calcite-slider]: last tick value generated can be greater than slider max" (or something similar). That issue will document the behavior you noticed here and propose a possible fix.

2021-11-03 00:55 UTC, caripizza approved these changes
Thanks @anveshmekala, just a tiny last comment 👍

2021-11-03 00:55 UTC, caripizza commented on src/components/calcite-slider/calcite-slider.e2e.ts
> +  it("should cap the rendered last tick label to the slider's provided max #3142", async () => {
nitpick: can you remove the issue number from the test title?

2021-11-03 16:32 UTC, merged