fix(link): ensures component works with non user-initiated click events
Esri/calcite-components pull request #5231
Opened 2022-08-27 00:39 UTC by Elijbet

**Related Issue:** #4212

## Summary

Adds a clickHandler that forwards the .click() to the internal link for non user-initiated events.

2022-08-30 01:33 UTC, Elijbet commented
A little perplexed by the test behavior: .click() results in 1 event being received each time, while page.$eval and .callMethod() receive it twice.

2022-08-30 19:33 UTC, jcfranco requested changes

2022-08-30 19:33 UTC, jcfranco commented on src/components/link/link.tsx
> +  /**
This doc/comment block is not needed. The handler name already expresses this information.

2022-08-30 19:33 UTC, jcfranco commented on src/components/link/link.tsx
> +    event.stopPropagation();
You still need to determine if the click came from the forwarded click or not. Only stop propagation if it's internal.

2022-08-30 19:33 UTC, jcfranco commented on src/components/link/link.tsx
> +    /* forwards the click() to the internal link for non user-initiated events */
Nitpick: use `//` for single-line comments

2022-08-31 20:21 UTC, jcfranco approved these changes
💥

2022-08-31 20:26 UTC, merged